name: service-4
on:
  workflow_call:


env: 
    ACTOR: $GITHUB_ACTOR

jobs:
  build_service_4_for_prod:
    if: ${{ github.ref_name == 'master' }}

    name: Master Build Service 4
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: service4
      working-directory: service_4
      run: |
        bash init.sh
        ${{ env.ACTOR }}





  build_service_4_for_QA:
    if: github.ref == 'refs/heads/develop'
    name: Develop Build Service 4
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: service4
      working-directory: service_4
      run: |
        bash init.sh
        ${{ env.ACTOR }}
