name: service-1
on:
  workflow_call:

env: 
    ACTOR: $GITHUB_ACTOR
     
jobs:
  build_service_1_for_prod:
    if: ${{ github.ref_name == 'master' }}

    name: master Build Service 1 
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: service1
      working-directory: service_1
      run: |
        ./init.sh ${{ env.branch }}
        ${{ env.ACTOR }}




  build_service_1_for_QA:
    if: github.ref == 'refs/heads/develop'
    name: develop Build Service 1
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: service1
      working-directory: service_1
      run: |
        ./init.sh ${{ env.branch }}
        ${{ env.ACTOR }}