name: service-2
on:
  workflow_call:
     
jobs:
  build_service_2_for_prod:
    if: ${{ github.ref_name == 'master' }}

    name: Build Service 2
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: service2
      working-directory: service_2
      run: |
        bash init.sh





  build_service_2_for_QA:
    if: github.ref == 'refs/heads/develop'
    name: Build Service 2
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: service2
      working-directory: service_2
      run: |
        bash init.sh
