name: service-2
on:
  workflow_call:
     
jobs:
  build_service-2:
    name: Build service-2
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: service1
      working-directory: service_2
      run: |
        bash init.sh
