name: service-3
on:
  workflow_call:
     
jobs:
  build_service-3:
    name: Build service-3
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: service1
      working-directory: service_3
      run: |
        bash init.sh
