name: service-4
on:
  workflow_call:
     
jobs:
  build_service-4:
    name: Build service-4
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: service1
      working-directory: service_4
      run: |
        bash init.sh
